export { default as HomePage } from './home.page'
export { default as AuthPage } from './auth.page'
export { default as RegisterPage } from './register.page'
export { default as TemplateEditorPage } from './template.editor.page'
export { default as TemplatesPage } from './templates.page'
export { default as ParsePage } from './parse.page'
