export { default as Auth } from './auth.component'
export { default as Register } from './register.component'
export { default as ImgEditor } from './img.editor.component'
export { default as Header } from './header.component'
export { default as ProjectBlock } from './projectBlock.component'
export { default as CreateNewProject } from './createNewProject.component'
export { default as Footer } from './footer.component'
export { default as HistoryTable } from './historyTable.component'
